version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2019
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%npm-cache'
  - '%USERPROFILE%.electron'
  - '%USERPROFILE%AppDataLocalYarncache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn electron:build

test: off

artifacts:
- path: dist_electron/*.exe
  name: myartifact

deploy:
  release: rteach-helper-v$(appveyor_build_version)
  description: 'rteach-helper release'
  provider: GitHub
  auth_token:
    secure: M3bcUnBw72UDRwPCvjgWJrJC5jCQwW1WoiQSKOZK3GrvTPIILCuHtFP1XRSdX5b0
  artifacts: myartifact
  draft: false
  prerelease: false
  on:
    branch: master  